receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  otlp:
    endpoint: 0.0.0.0:4317
    tls:
      insecure: true
  loki:
    endpoint: http://dotwes-loki:3100/loki/api/v1/push
    format: json
    labels:
      resource:
        service.name: "dotwes"
        service.instance.id: "dotwes_${HOSTNAME}"

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus ]
    traces:
      receivers: [ otlp ]
      exporters: [ otlp ]
    logs:
      receivers: [ otlp ]
      exporters: [ loki ]