version: '3.9'

services:

  dotwes-redis:
    image: redis:6.2-alpine
    command: redis-server --save 20 1 --loglevel debug --requirepass LocalPass
    volumes:
      - cache:/data
    ports:
      - "6379:6379"
    networks:
      - dotwes-bridge

  dotwes-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString="dotwes-redis,password=LocalPass"
      - Port=5013
      - SeedNodeHostNames=dotwes-api:5013
      - ClientConnectionPort=5014
    scale: 1
    ports:
      - "80:80"
      - "5555:80"
      - "443:443"
      - "5014:5014"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - dotwes-bridge

  #dotwes-web:
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    #- ASPNETCORE_URLS=https://+:443;http://+:80
  #    #- ASPNETCORE_URLS=http://+:80
  #    #- ServerUrl=ws://dotwes-api:5014
  #  scale: 1
  #  ports:
  #    - "81:80"
  #    - "4433:443"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro